---
deployment:
  tasks:
    - export REPOPATH=/home/helijhrv/repositories/HeliosX
    - cd $REPOPATH
    - /bin/echo "Installing dependencies..."
    - npm install
    - /bin/echo "Building Next.js application..."
    - npm run build
    - /bin/echo "Deployment complete!"
