---
deployment:
  tasks:
    # Simple deployment script for HeliosX on cPanel
    # 1. Install all dependencies (including dev dependencies for build)
    - /bin/echo "Installing dependencies..."
    - npm install --legacy-peer-deps

    # 2. Build the Next.js app
    - /bin/echo "Building Next.js application..."
    - npm run build

    # Note:
    # - Your Node.js application in cPanel should be configured separately
    #   to use `server.js` as the startup file in the same directory.
    # - If you change commands here, commit & push, then click Deploy again in cPanel.


