export type ReviewLanguage = 'en' | 'es' | 'pt' | 'ru'

export type Review = {
  id: string
  productSlug: string
  authorName: string
  authorCredential?: string
  authorLocation?: string
  language: ReviewLanguage
  rating: 1 | 2 | 3 | 4 | 5
  title: string
  body: string
  datePublished: string
  verified: boolean
}

export const reviews: Review[] = [
  // ───── MEDUSA — ergonomic prismatic, adjustable working distance ─────
  {
    id: 'm-1',
    productSlug: 'medusa',
    authorName: 'Daniel R.',
    authorCredential: 'Plastic Surgery, PGY-5',
    authorLocation: 'Cleveland, OH',
    language: 'en',
    rating: 5,
    title: 'The adjustable working distance is real',
    body: 'I was skeptical the adjustable WD would feel as solid as a fixed system. After three months of long cases it has held its alignment across seated breast and standing flap work. I have not had to rebalance once. Lighter than I expected for a prismatic.',
    datePublished: '2026-03-14',
    verified: true,
  },
  {
    id: 'm-2',
    productSlug: 'medusa',
    authorName: 'Amelia K.',
    authorCredential: 'OB-GYN, MD',
    authorLocation: 'Toronto, ON',
    language: 'en',
    rating: 5,
    title: 'Finally a prismatic I can wear all day',
    body: 'Coming off a six-year-old Galilean set. The Medusa is heavier on paper but the prismatic optics let me sit upright instead of craning. Two clinic days plus a long case and I went home without a neck headache for the first time in months.',
    datePublished: '2026-02-09',
    verified: true,
  },
  {
    id: 'm-3',
    productSlug: 'medusa',
    authorName: 'Rafael M.',
    authorCredential: 'Cirujano Maxilofacial',
    authorLocation: 'Madrid, España',
    language: 'es',
    rating: 5,
    title: 'Calidad muy superior al precio',
    body: 'Compré las Medusa para casos de cirugía ortognática. La nitidez y el campo a 4.0x son comparables a marcas que cuestan el triple. El servicio para tomar las medidas fue rápido y la entrega llegó a Europa sin problemas. Recomendadas para residentes y adjuntos.',
    datePublished: '2026-01-22',
    verified: true,
  },
  {
    id: 'm-4',
    productSlug: 'medusa',
    authorName: 'Kenji T.',
    authorCredential: 'Hand Surgery Fellow',
    authorLocation: 'San Francisco, CA',
    language: 'en',
    rating: 4,
    title: 'Excellent optics, frame took a week to dial in',
    body: 'Image quality is genuinely premium. The only friction was finding the right frame and nose pad position for a long face. Support shipped a second pad set and the fit is now perfect. Knock one star off for the initial fiddle, but optics earn the five they take back.',
    datePublished: '2025-12-30',
    verified: true,
  },
  {
    id: 'm-5',
    productSlug: 'medusa',
    authorName: 'Priya N.',
    authorCredential: 'Cardiothoracic Attending',
    authorLocation: 'Houston, TX',
    language: 'en',
    rating: 5,
    title: 'Replaced a $4.8k pair, no regrets',
    body: 'I lost my old loupes in transit between hospitals. Tried Medusa expecting to upgrade later. Six months in and the upgrade never happened because I do not need to. Field of view at 5.0x is wide enough for a CABG and the WD adjustment is a real differentiator on a tall table.',
    datePublished: '2026-04-18',
    verified: true,
  },
  {
    id: 'm-6',
    productSlug: 'medusa',
    authorName: 'Lucas P.',
    authorCredential: 'Cirurgião Plástico',
    authorLocation: 'São Paulo, Brasil',
    language: 'pt',
    rating: 5,
    title: 'Ótimo custo-benefício para uso diário',
    body: 'Trabalho com rinoplastia e mastoplastia. As Medusa têm uma profundidade de campo que me deixa confortável entre dois e três planos sem trocar de instrumento. A distância de trabalho ajustável é o ponto que mais me ajudou na coluna. Entrega para o Brasil demorou três semanas mas chegou intacta.',
    datePublished: '2026-03-02',
    verified: true,
  },
  {
    id: 'm-7',
    productSlug: 'medusa',
    authorName: 'Marcus W.',
    authorCredential: 'Vascular Surgery Attending',
    authorLocation: 'Chicago, IL',
    language: 'en',
    rating: 4,
    title: 'Good buy if you accept the IPD lock-in',
    body: 'Optics are excellent and the price is fair. One caution: the IPD is set at order time, so if you wear them on a colleague during a rough case they will not work for them. That is true of most prismatics, but worth noting.',
    datePublished: '2026-01-08',
    verified: true,
  },
  {
    id: 'm-8',
    productSlug: 'medusa',
    authorName: 'Elena V.',
    authorCredential: 'Микрохирург',
    authorLocation: 'Москва, Россия',
    language: 'ru',
    rating: 5,
    title: 'Оптика на уровне топовых брендов',
    body: 'Покупала для работы в реконструктивной микрохирургии. Поле зрения и резкость на 5.0x на уровне немецких аналогов в три-четыре раза дороже. Регулируемое рабочее расстояние действительно полезно, особенно когда чередуешь сидячие и стоячие процедуры. Поддержка ответила на письма быстро.',
    datePublished: '2026-02-25',
    verified: true,
  },
  {
    id: 'm-9',
    productSlug: 'medusa',
    authorName: 'Jessica T.',
    authorCredential: 'General Surgery, PGY-3',
    authorLocation: 'Boston, MA',
    language: 'en',
    rating: 5,
    title: 'Resident salary friendly without feeling cheap',
    body: 'I was using a borrowed pair for a year. Bought Medusa at 4.0x because attendings on the service kept asking what I was wearing. The fit clinic was thorough and the loupes arrived built around my actual measurements, not a generic preset. Real upgrade.',
    datePublished: '2026-04-03',
    verified: true,
  },
  {
    id: 'm-10',
    productSlug: 'medusa',
    authorName: 'Brian L.',
    authorCredential: 'ENT Attending',
    authorLocation: 'Seattle, WA',
    language: 'en',
    rating: 3,
    title: 'Great optics, light mount is a separate purchase',
    body: 'Setup is solid for the price. Just be aware the LED light source is not included and that should be more obvious on the product page. Once I added a third party light the rig is great. Optics-only review would be a five.',
    datePublished: '2026-03-21',
    verified: true,
  },

  // ───── APOLLO — ergonomic prismatic ─────
  {
    id: 'a-1',
    productSlug: 'apollo',
    authorName: 'Sarah H.',
    authorCredential: 'Oral Maxillofacial Surgery, PGY-4',
    authorLocation: 'Philadelphia, PA',
    language: 'en',
    rating: 5,
    title: 'The frame is the surprise',
    body: 'The Apollo frame fits flat against my face better than the borrowed Orascoptic pair I had been using. At 4.0x there is no edge softness and the image is even from corner to corner. Worth every dollar against the trainee budget.',
    datePublished: '2026-04-11',
    verified: true,
  },
  {
    id: 'a-2',
    productSlug: 'apollo',
    authorName: 'Mateo R.',
    authorCredential: 'Odontólogo',
    authorLocation: 'Buenos Aires, Argentina',
    language: 'es',
    rating: 5,
    title: 'Posturalmente cambió mi día clínico',
    body: 'Hago endodoncia y restauración estética. Con las Apollo a 4.0x trabajo erguido y termino el día sin la rigidez cervical de siempre. La calidad del campo es nítida hasta los bordes. Buena opción para colegas de Latinoamérica que no quieren pagar precios europeos.',
    datePublished: '2026-02-18',
    verified: true,
  },
  {
    id: 'a-3',
    productSlug: 'apollo',
    authorName: 'James M.',
    authorCredential: 'Plastic Surgery Attending',
    authorLocation: 'Atlanta, GA',
    language: 'en',
    rating: 5,
    title: 'Sharper than my old SurgiTel at 5.0x',
    body: 'I do not say that lightly. Replaced a 7-year-old SurgiTel pair. The Apollo 5.0x renders fine vessels with better contrast and the frame stays in place during long aesthetic cases. The custom IPD measurement process was meticulous.',
    datePublished: '2026-03-26',
    verified: true,
  },
  {
    id: 'a-4',
    productSlug: 'apollo',
    authorName: 'Hannah P.',
    authorCredential: 'Dental Student, D4',
    authorLocation: 'Ann Arbor, MI',
    language: 'en',
    rating: 5,
    title: 'Got me through finals and into rotations',
    body: 'I was the cheapest pair in clinic for a year. Saved up and got Apollo at 3.0x. The difference in fatigue at the end of a six-hour clinic day is real. Two attendings have asked me where I bought them since I started wearing them.',
    datePublished: '2026-01-15',
    verified: true,
  },
  {
    id: 'a-5',
    productSlug: 'apollo',
    authorName: 'Aleksandr V.',
    authorCredential: 'Стоматолог',
    authorLocation: 'Санкт-Петербург, Россия',
    language: 'ru',
    rating: 4,
    title: 'Отличная оптика, доставка долгая',
    body: 'Купил Apollo 4.0x. Качество изображения отличное, в комплекте все необходимое для измерений. Минус только в логистике до России - заняло около четырех недель. Сами линзы и оправа на уровне дорогих немецких брендов.',
    datePublished: '2026-02-04',
    verified: true,
  },
  {
    id: 'a-6',
    productSlug: 'apollo',
    authorName: 'Olivia C.',
    authorCredential: 'Endodontist',
    authorLocation: 'Denver, CO',
    language: 'en',
    rating: 5,
    title: 'Sharp enough for canal work without a microscope',
    body: 'I scope the difficult ones but on routine cases the Apollo at 5.0x with a good headlamp is enough. Crisp magnification, no rainbow fringe at the edges. The price-to-value ratio is the best I have seen since I started practicing in 2015.',
    datePublished: '2026-04-22',
    verified: true,
  },
  {
    id: 'a-7',
    productSlug: 'apollo',
    authorName: 'Tomás L.',
    authorCredential: 'Cirurgião Vascular',
    authorLocation: 'Lisboa, Portugal',
    language: 'pt',
    rating: 5,
    title: 'Qualidade óptica acima da expectativa',
    body: 'Recomendado por um colega que comprou as Medusa. Optei pelas Apollo a 5.0x por causa do meu trabalho com anastomoses. A nitidez e o conforto do quadro são excelentes. O atendimento ao cliente respondeu por email no mesmo dia para confirmar as medidas.',
    datePublished: '2026-03-09',
    verified: true,
  },
  {
    id: 'a-8',
    productSlug: 'apollo',
    authorName: 'Nathan G.',
    authorCredential: 'Otolaryngology Resident, PGY-2',
    authorLocation: 'Nashville, TN',
    language: 'en',
    rating: 4,
    title: 'Solid first set, single small fit issue',
    body: 'First loupes I have owned. The Apollo 3.0x fit was very close on arrival but the temple needed a small tweak. Support walked me through the adjustment over email. Image quality is excellent for the price tier.',
    datePublished: '2026-02-28',
    verified: true,
  },
  {
    id: 'a-9',
    productSlug: 'apollo',
    authorName: 'Rachel B.',
    authorCredential: 'Hand Surgery Fellow',
    authorLocation: 'New York, NY',
    language: 'en',
    rating: 5,
    title: 'Same image quality as the Orascoptic I tried first',
    body: 'I demoed Orascoptic prismatic at a course. The Apollo 4.5x is at minimum as sharp at half the price. Frame is more comfortable on me, probably because IPD was custom not preset. Fellowship-budget friendly.',
    datePublished: '2026-04-29',
    verified: true,
  },
  {
    id: 'a-10',
    productSlug: 'apollo',
    authorName: 'David K.',
    authorCredential: 'Periodontist',
    authorLocation: 'Minneapolis, MN',
    language: 'en',
    rating: 5,
    title: 'Posture-positive prismatic at a fair price',
    body: 'Switched from Galilean after 14 years. Apollo at 4.0x lets me sit upright with my head tilted maybe 5 degrees. My old setup had me at 25. My PT thanked me by week three.',
    datePublished: '2026-03-15',
    verified: true,
  },

  // ───── GALILEO — affordable, lightweight, student-friendly ─────
  {
    id: 'g-1',
    productSlug: 'galileo',
    authorName: 'Emily R.',
    authorCredential: 'Dental Student, D3',
    authorLocation: 'Boston, MA',
    language: 'en',
    rating: 5,
    title: 'Student price that does not feel student-quality',
    body: 'I was about to buy a knockoff pair off Amazon. Friend talked me into Galileo at 2.5x. The image is genuinely good and the frame does not slide off when I lean over a mannequin. I have used them every clinic day for four months.',
    datePublished: '2026-04-07',
    verified: true,
  },
  {
    id: 'g-2',
    productSlug: 'galileo',
    authorName: 'Jorge S.',
    authorCredential: 'Estudiante de Odontología, 4to año',
    authorLocation: 'Ciudad de México, México',
    language: 'es',
    rating: 5,
    title: 'Calidad que no esperaba al precio',
    body: 'Las compré con mi beca. La diferencia con las lupas baratas que usé el primer año es notable: nitidez consistente y peso muy bajo. La asesoría para tomar la distancia interpupilar fue clara incluso en inglés. Recomendadas para colegas latinoamericanos con presupuesto limitado.',
    datePublished: '2026-01-30',
    verified: true,
  },
  {
    id: 'g-3',
    productSlug: 'galileo',
    authorName: 'Aisha M.',
    authorCredential: 'Dental Hygienist',
    authorLocation: 'Toronto, ON',
    language: 'en',
    rating: 5,
    title: 'Light enough I forget I am wearing them',
    body: 'I scale all day, six days a week. The Galileo 3.0x is light, balanced, and the working distance was dialed in correctly the first time. The fit team double-checked my PD before production which I appreciated.',
    datePublished: '2026-03-19',
    verified: true,
  },
  {
    id: 'g-4',
    productSlug: 'galileo',
    authorName: 'Michael T.',
    authorCredential: 'General Dentist',
    authorLocation: 'Portland, OR',
    language: 'en',
    rating: 4,
    title: 'Good daily driver, prefer prismatic for endo',
    body: 'I have Galileo 3.5x for routine work and switch to a borrowed prismatic for endodontics. For everything except canal work the Galileo is plenty and lighter than my old set. Solid choice for general practice.',
    datePublished: '2026-02-12',
    verified: true,
  },
  {
    id: 'g-5',
    productSlug: 'galileo',
    authorName: 'Sofia P.',
    authorCredential: 'Acadêmica de Odontologia',
    authorLocation: 'Porto Alegre, Brasil',
    language: 'pt',
    rating: 5,
    title: 'Acessível e bem feito',
    body: 'Comprei as Galileo 2.5x ainda no terceiro ano. A imagem é nítida e o peso é confortável para um dia inteiro de clínica. O processo de medição foi simples mesmo do Brasil. Indicaria para qualquer colega que está montando o kit de estudante.',
    datePublished: '2026-04-01',
    verified: true,
  },
  {
    id: 'g-6',
    productSlug: 'galileo',
    authorName: 'Caleb J.',
    authorCredential: 'Medical Student, M3',
    authorLocation: 'St. Louis, MO',
    language: 'en',
    rating: 5,
    title: 'Bought to try surgical sub-i, ended up loving them',
    body: 'I wanted to look serious during my surgery sub-internship without spending fellowship money. Galileo 2.5x got the job done and I still use them on my plastic surgery elective. They are not as sharp as a $3k prismatic, but they are 80% of the way there.',
    datePublished: '2026-03-04',
    verified: true,
  },
  {
    id: 'g-7',
    productSlug: 'galileo',
    authorName: 'Yelena K.',
    authorCredential: 'Стоматолог-гигиенист',
    authorLocation: 'Минск, Беларусь',
    language: 'ru',
    rating: 4,
    title: 'Хорошее соотношение цена-качество',
    body: 'Заказывала Galileo 3.0x для ежедневной работы. Лёгкие, не давят на нос даже после восьми часов. Звезду снимаю только потому, что доставка до Минска заняла больше времени, чем обещали. Сами лупы отличные.',
    datePublished: '2026-02-21',
    verified: true,
  },
  {
    id: 'g-8',
    productSlug: 'galileo',
    authorName: 'Brandon C.',
    authorCredential: 'Dental Student, D2',
    authorLocation: 'Los Angeles, CA',
    language: 'en',
    rating: 5,
    title: 'Wish I had bought these in D1',
    body: 'Spent my first year squinting. Galileo 3.0x changed how I see prep margins. My instructor noticed my preps improved the week I started wearing them. Fair price for a student loan budget.',
    datePublished: '2026-04-14',
    verified: true,
  },
  {
    id: 'g-9',
    productSlug: 'galileo',
    authorName: 'Hannah W.',
    authorCredential: 'Family Medicine Resident, PGY-1',
    authorLocation: 'Madison, WI',
    language: 'en',
    rating: 5,
    title: 'Useful even for non-surgical residencies',
    body: 'I do skin biopsies and minor wound care in clinic. The Galileo 2.5x is light enough I forget I have them on and they actually help me read derm features. Did not realize how much I needed loupes until I had them.',
    datePublished: '2026-01-11',
    verified: true,
  },
  {
    id: 'g-10',
    productSlug: 'galileo',
    authorName: 'Andre L.',
    authorCredential: 'Dental Hygienist',
    authorLocation: 'Houston, TX',
    language: 'en',
    rating: 3,
    title: 'Honest 3 stars: optics good, frame style limited',
    body: 'Loupes themselves are great for the price. Wish there were more frame color options for the H1 model. Function over fashion is fine but a couple more choices would not hurt. Optics earn the price tier.',
    datePublished: '2026-03-28',
    verified: true,
  },

  // ───── NEWTON — ultra-light, daily-driver ─────
  {
    id: 'n-1',
    productSlug: 'newton',
    authorName: 'Megan F.',
    authorCredential: 'Dental Hygienist',
    authorLocation: 'Phoenix, AZ',
    language: 'en',
    rating: 5,
    title: 'The lightest pair I have ever worn',
    body: 'After 12 years of hygiene I have tried five brands. Newton at 2.5x is the lightest of any of them and the optics are as good as my old SurgiTel that cost three times more. Zero neck fatigue at end of shift.',
    datePublished: '2026-04-05',
    verified: true,
  },
  {
    id: 'n-2',
    productSlug: 'newton',
    authorName: 'Diego A.',
    authorCredential: 'Higienista Dental',
    authorLocation: 'Barcelona, España',
    language: 'es',
    rating: 5,
    title: 'Cómodas para días largos',
    body: 'Trabajo cuarenta horas a la semana en higiene dental. Las Newton a 3.0x son ligeras y la calidad óptica es muy buena. Mi cuello agradece el cambio. Recomendable para colegas que pasan el día agachados sobre el paciente.',
    datePublished: '2026-02-15',
    verified: true,
  },
  {
    id: 'n-3',
    productSlug: 'newton',
    authorName: 'Jasmine T.',
    authorCredential: 'Dental Student, D3',
    authorLocation: 'Chicago, IL',
    language: 'en',
    rating: 5,
    title: 'My everyday loupes for the rest of school',
    body: 'I started with no loupes, then got a cheap pair, then switched to Newton 3.0x mid-D3. Difference is night and day in clarity. They are featherweight - I genuinely forget they are on my face during a long restorative session.',
    datePublished: '2026-03-22',
    verified: true,
  },
  {
    id: 'n-4',
    productSlug: 'newton',
    authorName: 'Rohan K.',
    authorCredential: 'General Dentist',
    authorLocation: 'London, UK',
    language: 'en',
    rating: 4,
    title: 'Great for clinic, supplement with prismatic for complex work',
    body: 'Newton 3.5x is my daily clinic loupe. Crisp at the price, very light. For full mouth rehab or microendo I use a prismatic separate set. Honest review: do not expect 5x prismatic clarity, but at this price point you should not.',
    datePublished: '2026-01-19',
    verified: true,
  },
  {
    id: 'n-5',
    productSlug: 'newton',
    authorName: 'Beatriz F.',
    authorCredential: 'Cirurgiã-Dentista',
    authorLocation: 'Rio de Janeiro, Brasil',
    language: 'pt',
    rating: 5,
    title: 'Surpresa positiva pelo preço',
    body: 'Comprei sem grandes expectativas pelo preço, esperando algo só funcional. As Newton 2.5x são bem leves, com imagem nítida e quadro confortável. Para uso diário em clínica geral atendem perfeitamente. Bom para quem está começando.',
    datePublished: '2026-04-20',
    verified: true,
  },
  {
    id: 'n-6',
    productSlug: 'newton',
    authorName: 'Vladimir S.',
    authorCredential: 'Стоматолог',
    authorLocation: 'Алматы, Казахстан',
    language: 'ru',
    rating: 5,
    title: 'Лёгкие и резкие',
    body: 'Использую Newton 3.0x уже три месяца. Очень лёгкие, носить весь день удобно. Качество оптики выше, чем я ожидал за такие деньги. Хорошая альтернатива дорогим европейским моделям для повседневной практики.',
    datePublished: '2026-03-07',
    verified: true,
  },
  {
    id: 'n-7',
    productSlug: 'newton',
    authorName: 'Tasha M.',
    authorCredential: 'Dental Hygienist',
    authorLocation: 'Seattle, WA',
    language: 'en',
    rating: 5,
    title: 'Replaced a $1,800 pair with these',
    body: 'My old pair broke. Manager said get whatever fits the budget. I gambled on Newton 2.5x. Six weeks in I prefer them: lighter, cleaner image, fit is better. Not sure why I paid 1800 the first time.',
    datePublished: '2026-02-08',
    verified: true,
  },
  {
    id: 'n-8',
    productSlug: 'newton',
    authorName: 'Eric L.',
    authorCredential: 'Pediatric Dentist',
    authorLocation: 'San Diego, CA',
    language: 'en',
    rating: 5,
    title: 'Light enough that even uncooperative kids do not yank them',
    body: 'Sounds silly but the previous pair I wore had heavy temples and got grabbed by every toddler in the chair. Newton sits tight, no swing. Optics on 3.0x are perfect for pediatric work. Specific use case, perfect fit.',
    datePublished: '2026-04-24',
    verified: true,
  },
  {
    id: 'n-9',
    productSlug: 'newton',
    authorName: 'Caroline N.',
    authorCredential: 'Dental Hygienist',
    authorLocation: 'Calgary, AB',
    language: 'en',
    rating: 4,
    title: 'Light, sharp, just wish the case was nicer',
    body: 'Loupes themselves are excellent. The included case feels like an afterthought. Picked up a hard case separately. Subtracting one star for that, full marks on the optics and weight.',
    datePublished: '2026-03-17',
    verified: true,
  },
  {
    id: 'n-10',
    productSlug: 'newton',
    authorName: 'Mohammed Q.',
    authorCredential: 'General Dentist',
    authorLocation: 'Dubai, UAE',
    language: 'en',
    rating: 5,
    title: 'Excellent value, shipping was smooth',
    body: 'Ordered to the UAE. Measurement instructions were clear and the loupes arrived in three weeks. Newton 3.0x is sharp and the frame fits well. Recommended for any clinician in the region looking for premium quality at a fair price.',
    datePublished: '2026-01-26',
    verified: true,
  },

  // ───── KEPLER — high-magnification, microsurgery ─────
  {
    id: 'k-1',
    productSlug: 'kepler',
    authorName: 'Nicholas A.',
    authorCredential: 'Ophthalmic Surgeon',
    authorLocation: 'Baltimore, MD',
    language: 'en',
    rating: 5,
    title: '6.0x with a usable field is rare at this price',
    body: 'I do a lot of oculoplastic work that wants more than 4.5x but does not warrant a microscope setup. Kepler at 6.0x has a usable field and the contrast holds at the edges. Glad I tried it instead of buying another Designs for Vision set.',
    datePublished: '2026-04-09',
    verified: true,
  },
  {
    id: 'k-2',
    productSlug: 'kepler',
    authorName: 'Linda B.',
    authorCredential: 'Hand Surgery Attending',
    authorLocation: 'Pittsburgh, PA',
    language: 'en',
    rating: 5,
    title: 'Real microsurgery option at half the usual price',
    body: 'I trained on a Zeiss scope and use loupes for digital nerve work. Kepler 5.0x renders epineurium clearly, comparable to my old high-end Galilean. The price difference paid for two trips to AAOS.',
    datePublished: '2026-03-12',
    verified: true,
  },
  {
    id: 'k-3',
    productSlug: 'kepler',
    authorName: 'Felipe G.',
    authorCredential: 'Cirujano Plástico',
    authorLocation: 'Bogotá, Colombia',
    language: 'es',
    rating: 5,
    title: 'Alto aumento sin sacrificar campo',
    body: 'Para cirugía de mano y microcirugía reconstructiva. Las Kepler 5.0x tienen un campo muy aceptable y la profundidad es suficiente para anastomosis. La asistencia para tomar las medidas fue excelente y la entrega a Colombia llegó bien.',
    datePublished: '2026-02-23',
    verified: true,
  },
  {
    id: 'k-4',
    productSlug: 'kepler',
    authorName: 'Patricia M.',
    authorCredential: 'ENT Microvascular Fellow',
    authorLocation: 'Miami, FL',
    language: 'en',
    rating: 5,
    title: 'Use them for free-flap planning every week',
    body: 'I needed something I could wear into the OR for flap inset where the microscope is overkill. Kepler 6.0x is what I picked and I have not regretted it. Sharp, well balanced, IPD was dead on out of the box.',
    datePublished: '2026-04-26',
    verified: true,
  },
  {
    id: 'k-5',
    productSlug: 'kepler',
    authorName: 'Sergei B.',
    authorCredential: 'Сосудистый хирург',
    authorLocation: 'Новосибирск, Россия',
    language: 'ru',
    rating: 4,
    title: 'Качественная оптика для своей цены',
    body: 'Заказал Kepler 5.0x для работы с мелкими сосудами. Изображение чёткое, поле зрения нормальное на этом увеличении. Минус только небольшая адаптация к рамке - первые пару дней давила переносицу, потом привык. Поддержка предложила другие подушечки.',
    datePublished: '2026-01-14',
    verified: true,
  },
  {
    id: 'k-6',
    productSlug: 'kepler',
    authorName: 'Henrique D.',
    authorCredential: 'Cirurgião Cardíaco',
    authorLocation: 'Belo Horizonte, Brasil',
    language: 'pt',
    rating: 5,
    title: 'Excelente para cirurgia coronariana',
    body: 'Trabalho com revascularização do miocárdio. As Kepler 5.0x permitem ver as anastomoses com nitidez sem precisar do microscópio para casos rotineiros. Compra que valeu cada centavo. O suporte respondeu em português ao meu email.',
    datePublished: '2026-03-30',
    verified: true,
  },
  {
    id: 'k-7',
    productSlug: 'kepler',
    authorName: 'Andrew R.',
    authorCredential: 'Vascular Surgery, PGY-6',
    authorLocation: 'Houston, TX',
    language: 'en',
    rating: 4,
    title: 'Great optics, heavier than the lighter models',
    body: 'No surprise that 5.0x prismatic is heavier than 2.5x Galilean. Worth it for the resolution. Drop one star only because the weight is real after a full open AAA case. Not a flaw, just physics.',
    datePublished: '2026-02-19',
    verified: true,
  },
  {
    id: 'k-8',
    productSlug: 'kepler',
    authorName: 'Lauren V.',
    authorCredential: 'Plastic Surgery Attending',
    authorLocation: 'Charlotte, NC',
    language: 'en',
    rating: 5,
    title: 'Best price-to-resolution ratio I have found',
    body: 'I do hand and microsurgery reconstruction. Kepler 6.0x is comparable to my old Designs for Vision pair at less than half the price. The fit measurement process is more thorough than the big brands I have ordered from.',
    datePublished: '2026-04-13',
    verified: true,
  },
  {
    id: 'k-9',
    productSlug: 'kepler',
    authorName: 'Robert C.',
    authorCredential: 'Oculoplastic Surgeon',
    authorLocation: 'Toronto, ON',
    language: 'en',
    rating: 5,
    title: 'Crisp at 4.0x for daily lid work',
    body: 'I picked 4.0x for lid and lacrimal cases. Field is wide, edges are sharp, depth of field is forgiving. Replaced a 5-year-old prismatic that was due for a service anyway. Good move for the budget.',
    datePublished: '2026-03-05',
    verified: true,
  },
  {
    id: 'k-10',
    productSlug: 'kepler',
    authorName: 'Naomi K.',
    authorCredential: 'Plastic Surgery Fellow',
    authorLocation: 'Boston, MA',
    language: 'en',
    rating: 5,
    title: 'Fellowship-affordable microsurgery loupes',
    body: 'Could not justify $4-5k as a fellow. Kepler 5.0x has done everything I have needed for replants and digit-level work. Image quality is in the same class as the high-end set my attending wears. Genuinely impressed.',
    datePublished: '2026-04-30',
    verified: true,
  },
]

export function getProductReviews(slug: string): Review[] {
  return reviews
    .filter((review) => review.productSlug === slug)
    .sort((a, b) => b.datePublished.localeCompare(a.datePublished))
}

export function getProductAggregateRating(slug: string): {
  ratingValue: number
  reviewCount: number
} | null {
  const productReviews = getProductReviews(slug)
  if (productReviews.length === 0) return null
  const total = productReviews.reduce((sum, review) => sum + review.rating, 0)
  const average = total / productReviews.length
  return {
    ratingValue: Math.round(average * 10) / 10,
    reviewCount: productReviews.length,
  }
}
